[package]
name = "sigma-compiler"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Crate for automatically generating code for sigma zero-knowledge proof protocols of more complex statements than are supported by the sigma-proofs crate.  The statements given to this crate are compiled into statements about linear combinations of points, and transformed into the sigma-proofs API."

[dependencies]
group = "0.13"
rand = "0.8.5"
sigma-compiler-derive = { path = "sigma-compiler-derive" }
sigma-proofs = { path = "../sigma-proofs" }
subtle = "2.6"

[dev-dependencies]
curve25519-dalek = { version = "4", features = [ "group", "rand_core", "digest" ] }
sha2 = "0.10"
spongefish = {path = "../spongefish/spongefish",  features = ["curve25519-dalek"] }

[features]
# Dump (to stdout or to a string) the value of the instance on both the
# prover's and verifier's side.  They should match.
dump = [ "sigma-compiler-derive/dump" ]
# default = ["dump"]
